FROM golang:latest AS build

WORKDIR /app

COPY . ./

RUN go mod vendor

RUN go build -o /kyc cmd/migrations/main.go

RUN chmod 755 cmd/migrations/migrations_up.sh

ENTRYPOINT ["./cmd/migrations/migrations_up.sh"]